apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ansible-ee-t
  namespace: ansible-ee-build
spec:
  interceptors:
    - github:
        secretRef:
          secretName: github-trigger-secret
          secretKey: secretToken
        eventTypes:
        - push
    #https://tekton.dev/docs/triggers/interceptors/#cel-interceptors
    - cel:
        overlays:
        - key: short_sha
          expression: "body.head_commit.id.truncate(7)"
  bindings:
  - ref: ansible-ee-tb
  template:
    ref: ansible-ee-tt